package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/havlinj/featureflag-api/graph/model"
	"github.com/havlinj/featureflag-api/internal/audit"
)

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, id string) (*model.AuditLog, error) {
	if err := r.requireAuditReadAccess(ctx); err != nil {
		return nil, err
	}
	entry, err := r.audit.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return toAuditLogModel(entry), nil
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, filter *model.AuditLogsFilterInput, limit *int, offset *int) ([]*model.AuditLog, error) {
	if err := r.requireAuditReadAccess(ctx); err != nil {
		return nil, err
	}
	resolvedLimit := audit.DefaultListLimit
	if limit != nil {
		resolvedLimit = *limit
	}
	if resolvedLimit > audit.MaxListLimit {
		resolvedLimit = audit.MaxListLimit
	}
	resolvedOffset := 0
	if offset != nil {
		resolvedOffset = *offset
	}
	if resolvedOffset < 0 {
		return nil, audit.ErrNegativeOffset
	}

	var f audit.ListFilter
	if filter != nil {
		f = audit.ListFilter{
			Entity:  filter.Entity,
			Action:  filter.Action,
			ActorID: filter.ActorID,
		}
	}

	entries, err := r.audit.List(ctx, f, resolvedLimit, resolvedOffset)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AuditLog, 0, len(entries))
	for _, e := range entries {
		out = append(out, toAuditLogModel(e))
	}
	return out, nil
}
