package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/jan-havlin-dev/featureflag-api/graph/model"
	"github.com/jan-havlin-dev/featureflag-api/internal/auth"
	"github.com/jan-havlin-dev/featureflag-api/internal/users"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	userID, role, err := r.Users.Login(ctx, input.Email, input.Password)
	if err != nil {
		if err == users.ErrNotFound || err == users.ErrInvalidCredentials {
			return nil, err
		}
		return nil, err
	}
	token, err := auth.IssueToken(userID, role, r.JWTSecret, r.JWTExpiry)
	if err != nil {
		return nil, err
	}
	return &model.LoginPayload{Token: token}, nil
}
