package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/jan-havlin-dev/featureflag-api/graph"
	"github.com/jan-havlin-dev/featureflag-api/graph/model"
	"github.com/jan-havlin-dev/featureflag-api/internal/auth"
	"github.com/jan-havlin-dev/featureflag-api/internal/flags"
)

// CreateFlag is the resolver for the createFlag field.
func (r *mutationResolver) CreateFlag(ctx context.Context, input model.CreateFlagInput) (*model.FeatureFlag, error) {
	if _, err := auth.RequireRole(ctx, "admin", "developer"); err != nil {
		return nil, err
	}
	return r.Flags.CreateFlag(ctx, input)
}

// UpdateFlag is the resolver for the updateFlag field.
func (r *mutationResolver) UpdateFlag(ctx context.Context, input model.UpdateFlagInput) (*model.FeatureFlag, error) {
	if _, err := auth.RequireRole(ctx, "admin", "developer"); err != nil {
		return nil, err
	}
	return r.Flags.UpdateFlag(ctx, input)
}

// DeleteFlag is the resolver for the deleteFlag field.
func (r *mutationResolver) DeleteFlag(ctx context.Context, key string, environment string) (bool, error) {
	if _, err := auth.RequireRole(ctx, "admin", "developer"); err != nil {
		return false, err
	}
	return r.Flags.DeleteFlag(ctx, key, flags.DeploymentStage(environment))
}

// EvaluateFlag is the resolver for the evaluateFlag field.
func (r *queryResolver) EvaluateFlag(ctx context.Context, key string, evaluationContext model.EvaluationContextInput) (bool, error) {
	if _, err := auth.RequireRole(ctx, "admin", "developer", "viewer"); err != nil {
		return false, err
	}
	return r.Flags.EvaluateFlag(ctx, key, evaluationContext)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
