package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/jan-havlin-dev/featureflag-api/graph/model"
)

// CreateFlag is the resolver for the createFlag field.
func (r *mutationResolver) CreateFlag(ctx context.Context, input model.CreateFlagInput) (*model.FeatureFlag, error) {
	panic(fmt.Errorf("not implemented: CreateFlag - createFlag"))
}

// UpdateFlag is the resolver for the updateFlag field.
func (r *mutationResolver) UpdateFlag(ctx context.Context, input model.UpdateFlagInput) (*model.FeatureFlag, error) {
	panic(fmt.Errorf("not implemented: UpdateFlag - updateFlag"))
}

// EvaluateFlag is the resolver for the evaluateFlag field.
func (r *queryResolver) EvaluateFlag(ctx context.Context, key string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: EvaluateFlag - evaluateFlag"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
