// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateExperimentInput struct {
	Key         string                    `json:"key"`
	Environment string                    `json:"environment"`
	Variants    []*ExperimentVariantInput `json:"variants"`
}

type CreateFlagInput struct {
	Key             string           `json:"key"`
	Description     *string          `json:"description,omitempty"`
	Environment     string           `json:"environment"`
	RolloutStrategy *RolloutStrategy `json:"rolloutStrategy,omitempty"`
	Rules           []*RuleInput     `json:"rules,omitempty"`
}

type CreateUserInput struct {
	Email    string  `json:"email"`
	Role     Role    `json:"role"`
	Password *string `json:"password,omitempty"`
}

type EvaluationContextInput struct {
	UserID string  `json:"userId"`
	Email  *string `json:"email,omitempty"`
}

type Experiment struct {
	ID          string `json:"id"`
	Key         string `json:"key"`
	Environment string `json:"environment"`
}

type ExperimentVariant struct {
	ID           string `json:"id"`
	ExperimentID string `json:"experimentId"`
	Name         string `json:"name"`
	Weight       int    `json:"weight"`
}

type ExperimentVariantInput struct {
	Name   string `json:"name"`
	Weight int    `json:"weight"`
}

type FeatureFlag struct {
	ID              string          `json:"id"`
	Key             string          `json:"key"`
	Description     *string         `json:"description,omitempty"`
	Enabled         bool            `json:"enabled"`
	Environment     string          `json:"environment"`
	RolloutStrategy RolloutStrategy `json:"rolloutStrategy"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginPayload struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}

type RuleInput struct {
	Type  RolloutRuleType `json:"type"`
	Value string          `json:"value"`
}

type UpdateFlagInput struct {
	Key     string       `json:"key"`
	Enabled bool         `json:"enabled"`
	Rules   []*RuleInput `json:"rules,omitempty"`
}

type UpdateUserInput struct {
	ID       string  `json:"id"`
	Email    *string `json:"email,omitempty"`
	Role     *Role   `json:"role,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Role      Role   `json:"role"`
	CreatedAt string `json:"createdAt"`
}

type Role string

const (
	RoleAdmin     Role = "admin"
	RoleDeveloper Role = "developer"
	RoleViewer    Role = "viewer"
)

var AllRole = []Role{
	RoleAdmin,
	RoleDeveloper,
	RoleViewer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleDeveloper, RoleViewer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RolloutRuleType string

const (
	RolloutRuleTypePercentage RolloutRuleType = "PERCENTAGE"
	RolloutRuleTypeAttribute  RolloutRuleType = "ATTRIBUTE"
)

var AllRolloutRuleType = []RolloutRuleType{
	RolloutRuleTypePercentage,
	RolloutRuleTypeAttribute,
}

func (e RolloutRuleType) IsValid() bool {
	switch e {
	case RolloutRuleTypePercentage, RolloutRuleTypeAttribute:
		return true
	}
	return false
}

func (e RolloutRuleType) String() string {
	return string(e)
}

func (e *RolloutRuleType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RolloutRuleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RolloutRuleType", str)
	}
	return nil
}

func (e RolloutRuleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RolloutRuleType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RolloutRuleType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RolloutStrategy string

const (
	RolloutStrategyNone       RolloutStrategy = "NONE"
	RolloutStrategyPercentage RolloutStrategy = "PERCENTAGE"
	RolloutStrategyAttribute  RolloutStrategy = "ATTRIBUTE"
)

var AllRolloutStrategy = []RolloutStrategy{
	RolloutStrategyNone,
	RolloutStrategyPercentage,
	RolloutStrategyAttribute,
}

func (e RolloutStrategy) IsValid() bool {
	switch e {
	case RolloutStrategyNone, RolloutStrategyPercentage, RolloutStrategyAttribute:
		return true
	}
	return false
}

func (e RolloutStrategy) String() string {
	return string(e)
}

func (e *RolloutStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RolloutStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RolloutStrategy", str)
	}
	return nil
}

func (e RolloutStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RolloutStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RolloutStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
