// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateFlagInput struct {
	Key         string  `json:"key"`
	Description *string `json:"description,omitempty"`
	Environment string  `json:"environment"`
}

type CreateUserInput struct {
	Email string `json:"email"`
	Role  string `json:"role"`
}

type FeatureFlag struct {
	ID          string  `json:"id"`
	Key         string  `json:"key"`
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Environment string  `json:"environment"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginPayload struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateFlagInput struct {
	Key     string `json:"key"`
	Enabled bool   `json:"enabled"`
}

type UpdateUserInput struct {
	ID    string  `json:"id"`
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}
