#!/usr/bin/env bash
# Full test suite (same as CI): check, unit, Go integration, build, binary smoke, bash integration tests.
# For quick local validation without Docker/smoke, use test_all_quick.sh.
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

echo "=== 1/7 check"
"$SCRIPT_DIR/check.sh"
echo ""
echo "=== 2/7 unit tests"
"$SCRIPT_DIR/test_unit.sh"
echo ""
echo "=== 3/7 integration tests (Go)"
"$SCRIPT_DIR/test_integration.sh"
echo ""
echo "=== 4/7 coverage gate"
"$SCRIPT_DIR/test_coverage.sh"
echo ""
echo "=== 5/7 build"
"$SCRIPT_DIR/build.sh"
echo ""
echo "=== 6/7 binary smoke test"
"$SCRIPT_DIR/test_binary_smoke.sh"
echo ""
echo "=== 7/7 integration tests (bash)"
"$SCRIPT_DIR/integration/test_missing_jwt_secret.sh"
"$SCRIPT_DIR/integration/test_invalid_dsn.sh"
"$SCRIPT_DIR/integration/test_default_listen_addr.sh"
"$SCRIPT_DIR/integration/test_tls_config.sh"
echo ""
echo "=== All tests passed."
